In [1]:
import pandas as pd
import numpy as np

In [2]:
fil = pd.read_csv('sleep.csv')
fil.shape

(134, 20)

In [3]:
fil.head(5)

,Timestamp,Can we know your name please?,Your age,What is your typical time to go to sleep?,Average number of hours of sleep per night,How long does it take you to fall asleep after being in bed (Scaled in minutes)?,How many times ﻿do you wake up in between sleep?,Do you uncontrollably feel sleepy during the day/ class hours?,Do you use any fitness / sleep tracking device?,Sleep Environment [Do you watch TV/ use Mobile phones prior to sleep?],Sleep Environment [Do you sleep alone?],Sleep Environment [Is your study and sleep space separate?],How comfortable is your sleep area?,Does your sleeping habits affect your mood / academic performance / performance at work ?,Insomnia [Do you have trouble falling sleep?],Insomnia [Do you have trouble returning to sleep after being awaken during the night?],Insomnia [Do you use medications to help you sleep?],Is your sleep routine consistent ?,How would you rate your sleep?,Gender
0,2019/02/02 5:14:51 PM GMT+5:30,NaN,20,10 pm - 12 am,5-6,31 - 45,<2,Usually,No,Sometimes,Never,Sometimes,3,Sometimes,Seldom,No,No,Only on weekdays,3,Female
1,2019/02/02 5:24:09 PM GMT+5:30,_AP_The_Don,20,10 pm - 12 am,7-8,0 - 15,<2,Always,Yes,Yes,Yes,Never,2,Usually,No,No,No,No,4,Male
2,2019/02/02 5:32:44 PM GMT+5:30,Riyaz,20,10 pm - 12 am,5-6,0 - 15,<2,Always,No,Yes,Yes,Yes,5,Never,No,No,No,Yes,4,Male
3,2019/02/02 5:33:13 PM GMT+5:30,NaN,20,1 am,7-8,0 - 15,<2,Sometimes,No,Sometimes,Yes,Sometimes,5,Usually,No,No,No,Only on weekdays,4,NaN
4,2019/02/02 5:34:00 PM GMT+5:30,Hussain Imthiaz Hussain,17,Before 10 pm,7-8,0 - 15,<2,Rarely,No,Sometimes,Never,Never,4,Always,Seldom,Sometimes,Seldom,Yes,4,Male

In [4]:
drop_cols = fil.columns.values[0:2]
fil=fil.drop(columns=drop_cols)
fil.shape

(134, 18)

In [5]:
print fil.columns.values

['Your age' 'What is your typical time to go to sleep?'
 'Average number of hours of sleep per night'
 'How long does it take you to fall asleep after being in bed (Scaled in minutes)?'
 'How many times \xef\xbb\xbfdo you wake up in between sleep?'
 'Do you uncontrollably feel sleepy during the day/ class hours?'
 'Do you use any fitness / sleep tracking device?'
 'Sleep Environment [Do you watch TV/ use Mobile phones prior to sleep?]'
 'Sleep Environment [Do you sleep alone?]'
 'Sleep Environment [Is your study and sleep space separate?]'
 'How comfortable is your sleep area?'
 'Does your sleeping habits affect your mood / academic performance / performance at work ?'
 'Insomnia [Do you have trouble falling sleep?]'
 'Insomnia [Do you have trouble returning to sleep after being awaken during the night?]'
 'Insomnia [Do you use medications to help you sleep?]'
 'Is your sleep routine consistent ?' 'How would you rate your sleep?'
 'Gender']

In [6]:
fil.columns = ['age','time_sleep','no_of_hrs','minutes_to_sleep','wake_up','day_sleep','tracker','use_tv','sleep_alone','sep_sleep_place','comfort','perf','trouble_sleep','trouble_back_to_sleep','medication','routine','rate','gender']

In [7]:
fil.columns.values
fil.shape

(134, 18)

In [8]:
fil.columns.values

array(['age', 'time_sleep', 'no_of_hrs', 'minutes_to_sleep', 'wake_up',
       'day_sleep', 'tracker', 'use_tv', 'sleep_alone', 'sep_sleep_place',
       'comfort', 'perf', 'trouble_sleep', 'trouble_back_to_sleep',
       'medication', 'routine', 'rate', 'gender'], dtype=object)

In [9]:
fil.head(5)

,age,time_sleep,no_of_hrs,minutes_to_sleep,wake_up,day_sleep,tracker,use_tv,sleep_alone,sep_sleep_place,comfort,perf,trouble_sleep,trouble_back_to_sleep,medication,routine,rate,gender
0,20,10 pm - 12 am,5-6,31 - 45,<2,Usually,No,Sometimes,Never,Sometimes,3,Sometimes,Seldom,No,No,Only on weekdays,3,Female
1,20,10 pm - 12 am,7-8,0 - 15,<2,Always,Yes,Yes,Yes,Never,2,Usually,No,No,No,No,4,Male
2,20,10 pm - 12 am,5-6,0 - 15,<2,Always,No,Yes,Yes,Yes,5,Never,No,No,No,Yes,4,Male
3,20,1 am,7-8,0 - 15,<2,Sometimes,No,Sometimes,Yes,Sometimes,5,Usually,No,No,No,Only on weekdays,4,NaN
4,17,Before 10 pm,7-8,0 - 15,<2,Rarely,No,Sometimes,Never,Never,4,Always,Seldom,Sometimes,Seldom,Yes,4,Male

In [10]:
fil['gender'].fillna('Untold',inplace=True)

In [11]:
fil['gender']=np.where(fil['gender']=='Male',0,fil['gender'])
fil['gender']=np.where(fil['gender']=='Female',1,fil['gender'])
fil['gender']=np.where(fil['gender']=='Untold',2,fil['gender'])

In [12]:
fil.head(5)

,age,time_sleep,no_of_hrs,minutes_to_sleep,wake_up,day_sleep,tracker,use_tv,sleep_alone,sep_sleep_place,comfort,perf,trouble_sleep,trouble_back_to_sleep,medication,routine,rate,gender
0,20,10 pm - 12 am,5-6,31 - 45,<2,Usually,No,Sometimes,Never,Sometimes,3,Sometimes,Seldom,No,No,Only on weekdays,3,1
1,20,10 pm - 12 am,7-8,0 - 15,<2,Always,Yes,Yes,Yes,Never,2,Usually,No,No,No,No,4,0
2,20,10 pm - 12 am,5-6,0 - 15,<2,Always,No,Yes,Yes,Yes,5,Never,No,No,No,Yes,4,0
3,20,1 am,7-8,0 - 15,<2,Sometimes,No,Sometimes,Yes,Sometimes,5,Usually,No,No,No,Only on weekdays,4,2
4,17,Before 10 pm,7-8,0 - 15,<2,Rarely,No,Sometimes,Never,Never,4,Always,Seldom,Sometimes,Seldom,Yes,4,0

In [13]:
fil['routine']=np.where(fil['routine']=='Yes',0,fil['routine'])
fil['routine']=np.where(fil['routine']=='Only on weekdays',1,fil['routine'])
fil['routine']=np.where(fil['routine']=='No',2,fil['routine'])

In [14]:
fil.head(5)

,age,time_sleep,no_of_hrs,minutes_to_sleep,wake_up,day_sleep,tracker,use_tv,sleep_alone,sep_sleep_place,comfort,perf,trouble_sleep,trouble_back_to_sleep,medication,routine,rate,gender
0,20,10 pm - 12 am,5-6,31 - 45,<2,Usually,No,Sometimes,Never,Sometimes,3,Sometimes,Seldom,No,No,1,3,1
1,20,10 pm - 12 am,7-8,0 - 15,<2,Always,Yes,Yes,Yes,Never,2,Usually,No,No,No,2,4,0
2,20,10 pm - 12 am,5-6,0 - 15,<2,Always,No,Yes,Yes,Yes,5,Never,No,No,No,0,4,0
3,20,1 am,7-8,0 - 15,<2,Sometimes,No,Sometimes,Yes,Sometimes,5,Usually,No,No,No,1,4,2
4,17,Before 10 pm,7-8,0 - 15,<2,Rarely,No,Sometimes,Never,Never,4,Always,Seldom,Sometimes,Seldom,0,4,0

In [15]:
fil['medication']=np.where(fil['medication']=='Yes',0,fil['medication'])
fil['medication']=np.where(fil['medication']=='Sometimes',1,fil['medication'])
fil['medication']=np.where(fil['medication']=='Seldom',2,fil['medication'])
fil['medication']=np.where(fil['medication']=='No',3,fil['medication'])

In [16]:
fil.head(5)

,age,time_sleep,no_of_hrs,minutes_to_sleep,wake_up,day_sleep,tracker,use_tv,sleep_alone,sep_sleep_place,comfort,perf,trouble_sleep,trouble_back_to_sleep,medication,routine,rate,gender
0,20,10 pm - 12 am,5-6,31 - 45,<2,Usually,No,Sometimes,Never,Sometimes,3,Sometimes,Seldom,No,3,1,3,1
1,20,10 pm - 12 am,7-8,0 - 15,<2,Always,Yes,Yes,Yes,Never,2,Usually,No,No,3,2,4,0
2,20,10 pm - 12 am,5-6,0 - 15,<2,Always,No,Yes,Yes,Yes,5,Never,No,No,3,0,4,0
3,20,1 am,7-8,0 - 15,<2,Sometimes,No,Sometimes,Yes,Sometimes,5,Usually,No,No,3,1,4,2
4,17,Before 10 pm,7-8,0 - 15,<2,Rarely,No,Sometimes,Never,Never,4,Always,Seldom,Sometimes,2,0,4,0

In [17]:
fil.dtypes

age                       int64
time_sleep               object
no_of_hrs                object
minutes_to_sleep         object
wake_up                  object
day_sleep                object
tracker                  object
use_tv                   object
sleep_alone              object
sep_sleep_place          object
comfort                   int64
perf                     object
trouble_sleep            object
trouble_back_to_sleep    object
medication               object
routine                  object
rate                      int64
gender                   object
dtype: object

In [18]:
fil['trouble_back_to_sleep']=np.where(fil['trouble_back_to_sleep']=='Yes',0,fil['trouble_back_to_sleep'])
fil['trouble_back_to_sleep']=np.where(fil['trouble_back_to_sleep']=='Sometimes',1,fil['trouble_back_to_sleep'])
fil['trouble_back_to_sleep']=np.where(fil['trouble_back_to_sleep']=='Seldom',2,fil['trouble_back_to_sleep'])
fil['trouble_back_to_sleep']=np.where(fil['trouble_back_to_sleep']=='No',3,fil['trouble_back_to_sleep'])

In [19]:
fil.head(5)

,age,time_sleep,no_of_hrs,minutes_to_sleep,wake_up,day_sleep,tracker,use_tv,sleep_alone,sep_sleep_place,comfort,perf,trouble_sleep,trouble_back_to_sleep,medication,routine,rate,gender
0,20,10 pm - 12 am,5-6,31 - 45,<2,Usually,No,Sometimes,Never,Sometimes,3,Sometimes,Seldom,3,3,1,3,1
1,20,10 pm - 12 am,7-8,0 - 15,<2,Always,Yes,Yes,Yes,Never,2,Usually,No,3,3,2,4,0
2,20,10 pm - 12 am,5-6,0 - 15,<2,Always,No,Yes,Yes,Yes,5,Never,No,3,3,0,4,0
3,20,1 am,7-8,0 - 15,<2,Sometimes,No,Sometimes,Yes,Sometimes,5,Usually,No,3,3,1,4,2
4,17,Before 10 pm,7-8,0 - 15,<2,Rarely,No,Sometimes,Never,Never,4,Always,Seldom,1,2,0,4,0

In [20]:
fil['trouble_sleep']=np.where(fil['trouble_sleep']=='Yes',0,fil['trouble_sleep'])
fil['trouble_sleep']=np.where(fil['trouble_sleep']=='Sometimes',1,fil['trouble_sleep'])
fil['trouble_sleep']=np.where(fil['trouble_sleep']=='Seldom',2,fil['trouble_sleep'])
fil['trouble_sleep']=np.where(fil['trouble_sleep']=='No',3,fil['trouble_sleep'])

In [21]:
fil.head(5)

,age,time_sleep,no_of_hrs,minutes_to_sleep,wake_up,day_sleep,tracker,use_tv,sleep_alone,sep_sleep_place,comfort,perf,trouble_sleep,trouble_back_to_sleep,medication,routine,rate,gender
0,20,10 pm - 12 am,5-6,31 - 45,<2,Usually,No,Sometimes,Never,Sometimes,3,Sometimes,2,3,3,1,3,1
1,20,10 pm - 12 am,7-8,0 - 15,<2,Always,Yes,Yes,Yes,Never,2,Usually,3,3,3,2,4,0
2,20,10 pm - 12 am,5-6,0 - 15,<2,Always,No,Yes,Yes,Yes,5,Never,3,3,3,0,4,0
3,20,1 am,7-8,0 - 15,<2,Sometimes,No,Sometimes,Yes,Sometimes,5,Usually,3,3,3,1,4,2
4,17,Before 10 pm,7-8,0 - 15,<2,Rarely,No,Sometimes,Never,Never,4,Always,2,1,2,0,4,0

In [22]:
fil['perf']=np.where(fil['perf']=='Always',0,fil['perf'])
fil['perf']=np.where(fil['perf']=='Usually',1,fil['perf'])
fil['perf']=np.where(fil['perf']=='Sometimes',2,fil['perf'])
fil['perf']=np.where(fil['perf']=='Never',3,fil['perf'])

In [23]:
fil.head(5)

,age,time_sleep,no_of_hrs,minutes_to_sleep,wake_up,day_sleep,tracker,use_tv,sleep_alone,sep_sleep_place,comfort,perf,trouble_sleep,trouble_back_to_sleep,medication,routine,rate,gender
0,20,10 pm - 12 am,5-6,31 - 45,<2,Usually,No,Sometimes,Never,Sometimes,3,2,2,3,3,1,3,1
1,20,10 pm - 12 am,7-8,0 - 15,<2,Always,Yes,Yes,Yes,Never,2,1,3,3,3,2,4,0
2,20,10 pm - 12 am,5-6,0 - 15,<2,Always,No,Yes,Yes,Yes,5,3,3,3,3,0,4,0
3,20,1 am,7-8,0 - 15,<2,Sometimes,No,Sometimes,Yes,Sometimes,5,1,3,3,3,1,4,2
4,17,Before 10 pm,7-8,0 - 15,<2,Rarely,No,Sometimes,Never,Never,4,0,2,1,2,0,4,0

In [24]:
fil['sep_sleep_place']=np.where(fil['sep_sleep_place']=='Yes',0,fil['sep_sleep_place'])
fil['sep_sleep_place']=np.where(fil['sep_sleep_place']=='Sometimes',1,fil['sep_sleep_place'])
fil['sep_sleep_place']=np.where(fil['sep_sleep_place']=='Never',2,fil['sep_sleep_place'])

In [25]:
fil.head(5)

,age,time_sleep,no_of_hrs,minutes_to_sleep,wake_up,day_sleep,tracker,use_tv,sleep_alone,sep_sleep_place,comfort,perf,trouble_sleep,trouble_back_to_sleep,medication,routine,rate,gender
0,20,10 pm - 12 am,5-6,31 - 45,<2,Usually,No,Sometimes,Never,1,3,2,2,3,3,1,3,1
1,20,10 pm - 12 am,7-8,0 - 15,<2,Always,Yes,Yes,Yes,2,2,1,3,3,3,2,4,0
2,20,10 pm - 12 am,5-6,0 - 15,<2,Always,No,Yes,Yes,0,5,3,3,3,3,0,4,0
3,20,1 am,7-8,0 - 15,<2,Sometimes,No,Sometimes,Yes,1,5,1,3,3,3,1,4,2
4,17,Before 10 pm,7-8,0 - 15,<2,Rarely,No,Sometimes,Never,2,4,0,2,1,2,0,4,0

In [26]:
fil['sleep_alone']=np.where(fil['sleep_alone']=='Yes',0,fil['sleep_alone'])
fil['sleep_alone']=np.where(fil['sleep_alone']=='Sometimes',1,fil['sleep_alone'])
fil['sleep_alone']=np.where(fil['sleep_alone']=='Never',2,fil['sleep_alone'])

In [27]:
fil.head(5)

,age,time_sleep,no_of_hrs,minutes_to_sleep,wake_up,day_sleep,tracker,use_tv,sleep_alone,sep_sleep_place,comfort,perf,trouble_sleep,trouble_back_to_sleep,medication,routine,rate,gender
0,20,10 pm - 12 am,5-6,31 - 45,<2,Usually,No,Sometimes,2,1,3,2,2,3,3,1,3,1
1,20,10 pm - 12 am,7-8,0 - 15,<2,Always,Yes,Yes,0,2,2,1,3,3,3,2,4,0
2,20,10 pm - 12 am,5-6,0 - 15,<2,Always,No,Yes,0,0,5,3,3,3,3,0,4,0
3,20,1 am,7-8,0 - 15,<2,Sometimes,No,Sometimes,0,1,5,1,3,3,3,1,4,2
4,17,Before 10 pm,7-8,0 - 15,<2,Rarely,No,Sometimes,2,2,4,0,2,1,2,0,4,0

In [28]:
fil['use_tv']=np.where(fil['use_tv']=='Yes',0,fil['use_tv'])
fil['use_tv']=np.where(fil['use_tv']=='Sometimes',1,fil['use_tv'])
fil['use_tv']=np.where(fil['use_tv']=='Never',2,fil['use_tv'])

In [29]:
fil.head(5)

,age,time_sleep,no_of_hrs,minutes_to_sleep,wake_up,day_sleep,tracker,use_tv,sleep_alone,sep_sleep_place,comfort,perf,trouble_sleep,trouble_back_to_sleep,medication,routine,rate,gender
0,20,10 pm - 12 am,5-6,31 - 45,<2,Usually,No,1,2,1,3,2,2,3,3,1,3,1
1,20,10 pm - 12 am,7-8,0 - 15,<2,Always,Yes,0,0,2,2,1,3,3,3,2,4,0
2,20,10 pm - 12 am,5-6,0 - 15,<2,Always,No,0,0,0,5,3,3,3,3,0,4,0
3,20,1 am,7-8,0 - 15,<2,Sometimes,No,1,0,1,5,1,3,3,3,1,4,2
4,17,Before 10 pm,7-8,0 - 15,<2,Rarely,No,1,2,2,4,0,2,1,2,0,4,0

In [30]:
fil['tracker']=np.where(fil['tracker']=='Yes',0,fil['tracker'])
fil['tracker']=np.where(fil['tracker']=='No',1,fil['tracker'])

In [31]:
fil.head(5)

,age,time_sleep,no_of_hrs,minutes_to_sleep,wake_up,day_sleep,tracker,use_tv,sleep_alone,sep_sleep_place,comfort,perf,trouble_sleep,trouble_back_to_sleep,medication,routine,rate,gender
0,20,10 pm - 12 am,5-6,31 - 45,<2,Usually,1,1,2,1,3,2,2,3,3,1,3,1
1,20,10 pm - 12 am,7-8,0 - 15,<2,Always,0,0,0,2,2,1,3,3,3,2,4,0
2,20,10 pm - 12 am,5-6,0 - 15,<2,Always,1,0,0,0,5,3,3,3,3,0,4,0
3,20,1 am,7-8,0 - 15,<2,Sometimes,1,1,0,1,5,1,3,3,3,1,4,2
4,17,Before 10 pm,7-8,0 - 15,<2,Rarely,1,1,2,2,4,0,2,1,2,0,4,0

In [32]:
fil['day_sleep']=np.where(fil['day_sleep']=='Always',0,fil['day_sleep'])
fil['day_sleep']=np.where(fil['day_sleep']=='Usually',1,fil['day_sleep'])
fil['day_sleep']=np.where(fil['day_sleep']=='Sometimes',2,fil['day_sleep'])
fil['day_sleep']=np.where(fil['day_sleep']=='Rarely',3,fil['day_sleep'])
fil['day_sleep']=np.where(fil['day_sleep']=='Never',4,fil['day_sleep'])

In [33]:
fil.head(5)

,age,time_sleep,no_of_hrs,minutes_to_sleep,wake_up,day_sleep,tracker,use_tv,sleep_alone,sep_sleep_place,comfort,perf,trouble_sleep,trouble_back_to_sleep,medication,routine,rate,gender
0,20,10 pm - 12 am,5-6,31 - 45,<2,1,1,1,2,1,3,2,2,3,3,1,3,1
1,20,10 pm - 12 am,7-8,0 - 15,<2,0,0,0,0,2,2,1,3,3,3,2,4,0
2,20,10 pm - 12 am,5-6,0 - 15,<2,0,1,0,0,0,5,3,3,3,3,0,4,0
3,20,1 am,7-8,0 - 15,<2,2,1,1,0,1,5,1,3,3,3,1,4,2
4,17,Before 10 pm,7-8,0 - 15,<2,3,1,1,2,2,4,0,2,1,2,0,4,0

In [34]:
fil['wake_up']=np.where(fil['wake_up']=='<2',0,fil['wake_up'])
fil['wake_up']=np.where(fil['wake_up']=='3',1,fil['wake_up'])
fil['wake_up']=np.where(fil['wake_up']=='4',2,fil['wake_up'])
fil['wake_up']=np.where(fil['wake_up']=='5',3,fil['wake_up'])
fil['wake_up']=np.where(fil['wake_up']=='>5',4,fil['wake_up'])

In [35]:
fil.head(5)

,age,time_sleep,no_of_hrs,minutes_to_sleep,wake_up,day_sleep,tracker,use_tv,sleep_alone,sep_sleep_place,comfort,perf,trouble_sleep,trouble_back_to_sleep,medication,routine,rate,gender
0,20,10 pm - 12 am,5-6,31 - 45,0,1,1,1,2,1,3,2,2,3,3,1,3,1
1,20,10 pm - 12 am,7-8,0 - 15,0,0,0,0,0,2,2,1,3,3,3,2,4,0
2,20,10 pm - 12 am,5-6,0 - 15,0,0,1,0,0,0,5,3,3,3,3,0,4,0
3,20,1 am,7-8,0 - 15,0,2,1,1,0,1,5,1,3,3,3,1,4,2
4,17,Before 10 pm,7-8,0 - 15,0,3,1,1,2,2,4,0,2,1,2,0,4,0

In [36]:
fil['minutes_to_sleep']=np.where(fil['minutes_to_sleep']=='0 - 15',0,fil['minutes_to_sleep'])
fil['minutes_to_sleep']=np.where(fil['minutes_to_sleep']=='16 - 30',1,fil['minutes_to_sleep'])
fil['minutes_to_sleep']=np.where(fil['minutes_to_sleep']=='31 - 45',2,fil['minutes_to_sleep'])
fil['minutes_to_sleep']=np.where(fil['minutes_to_sleep']=='46 - 60',3,fil['minutes_to_sleep'])
fil['minutes_to_sleep']=np.where(fil['minutes_to_sleep']=='>60',4,fil['minutes_to_sleep'])

In [37]:
fil.head(5)

,age,time_sleep,no_of_hrs,minutes_to_sleep,wake_up,day_sleep,tracker,use_tv,sleep_alone,sep_sleep_place,comfort,perf,trouble_sleep,trouble_back_to_sleep,medication,routine,rate,gender
0,20,10 pm - 12 am,5-6,2,0,1,1,1,2,1,3,2,2,3,3,1,3,1
1,20,10 pm - 12 am,7-8,0,0,0,0,0,0,2,2,1,3,3,3,2,4,0
2,20,10 pm - 12 am,5-6,0,0,0,1,0,0,0,5,3,3,3,3,0,4,0
3,20,1 am,7-8,0,0,2,1,1,0,1,5,1,3,3,3,1,4,2
4,17,Before 10 pm,7-8,0,0,3,1,1,2,2,4,0,2,1,2,0,4,0

In [38]:
fil['no_of_hrs']=np.where(fil['no_of_hrs']=='<=4',0,fil['no_of_hrs'])
fil['no_of_hrs']=np.where(fil['no_of_hrs']=='5-6',1,fil['no_of_hrs'])
fil['no_of_hrs']=np.where(fil['no_of_hrs']=='7-8',2,fil['no_of_hrs'])
fil['no_of_hrs']=np.where(fil['no_of_hrs']=='>8',3,fil['no_of_hrs'])

In [39]:
fil.head(5)

,age,time_sleep,no_of_hrs,minutes_to_sleep,wake_up,day_sleep,tracker,use_tv,sleep_alone,sep_sleep_place,comfort,perf,trouble_sleep,trouble_back_to_sleep,medication,routine,rate,gender
0,20,10 pm - 12 am,1,2,0,1,1,1,2,1,3,2,2,3,3,1,3,1
1,20,10 pm - 12 am,2,0,0,0,0,0,0,2,2,1,3,3,3,2,4,0
2,20,10 pm - 12 am,1,0,0,0,1,0,0,0,5,3,3,3,3,0,4,0
3,20,1 am,2,0,0,2,1,1,0,1,5,1,3,3,3,1,4,2
4,17,Before 10 pm,2,0,0,3,1,1,2,2,4,0,2,1,2,0,4,0

In [40]:
fil['time_sleep']=np.where(fil['time_sleep']=='Before 10 pm',0,fil['time_sleep'])
fil['time_sleep']=np.where(fil['time_sleep']=='10 pm - 12 am',1,fil['time_sleep'])
fil['time_sleep']=np.where(fil['time_sleep']=='1 am',2,fil['time_sleep'])
fil['time_sleep']=np.where(fil['time_sleep']=='After 1 am',3,fil['time_sleep'])

In [41]:
fil.head(5)

,age,time_sleep,no_of_hrs,minutes_to_sleep,wake_up,day_sleep,tracker,use_tv,sleep_alone,sep_sleep_place,comfort,perf,trouble_sleep,trouble_back_to_sleep,medication,routine,rate,gender
0,20,1,1,2,0,1,1,1,2,1,3,2,2,3,3,1,3,1
1,20,1,2,0,0,0,0,0,0,2,2,1,3,3,3,2,4,0
2,20,1,1,0,0,0,1,0,0,0,5,3,3,3,3,0,4,0
3,20,2,2,0,0,2,1,1,0,1,5,1,3,3,3,1,4,2
4,17,0,2,0,0,3,1,1,2,2,4,0,2,1,2,0,4,0

In [42]:
fil.dtypes

age                       int64
time_sleep               object
no_of_hrs                object
minutes_to_sleep         object
wake_up                  object
day_sleep                object
tracker                  object
use_tv                   object
sleep_alone              object
sep_sleep_place          object
comfort                   int64
perf                     object
trouble_sleep            object
trouble_back_to_sleep    object
medication               object
routine                  object
rate                      int64
gender                   object
dtype: object

In [43]:
for i in fil.columns.values:
        fil[i]=fil[i].apply(pd.to_numeric)

In [44]:
fil.dtypes

age                      int64
time_sleep               int64
no_of_hrs                int64
minutes_to_sleep         int64
wake_up                  int64
day_sleep                int64
tracker                  int64
use_tv                   int64
sleep_alone              int64
sep_sleep_place          int64
comfort                  int64
perf                     int64
trouble_sleep            int64
trouble_back_to_sleep    int64
medication               int64
routine                  int64
rate                     int64
gender                   int64
dtype: object

In [45]:
temp=fil
temp1=fil
temp2=fil
fil.to_csv('sleep_cleaned.csv',index=False)

In [46]:
for i in temp.columns.values:
    temp[i] = temp[i] - temp[i].min(axis=0)
    temp[i] = temp[i]/(temp[i].max(axis=0)-temp[i].min(axis=0))

In [47]:
temp.shape
temp.to_csv('sleep_norm_min.csv',index=False)

In [48]:
for i in temp1.columns.values:
    temp1[i] = temp1[i] - temp1[i].max(axis=0)
    temp1[i] = temp[i]/(temp[i].max(axis=0)-temp[i].min(axis=0))

In [49]:
temp1.shape
temp1.to_csv('sleep_norm_max.csv',index=False)

In [50]:
for i in temp2.columns.values:
    temp2[i] = temp[i] - temp[i].mean(axis=0)
    temp2[i] = temp[i]/(temp[i].var(axis=0))

In [51]:
temp1.shape
temp1.to_csv('sleep_norm_var.csv',index=False)